
@startuml
hide circle
skinparam classAttributeIconSize 0
skinparam classNameBold true
skinparam monochrome true
skinparam roundCorner 8
skinparam defaultFontSize 13
skinparam classFontStyle Bold
skinparam defaultFontName Impact

class ComandoHandler ##[bold] {
    -comando: ComandoInfo
    -a_ejecutar: Comando
    +ejecutar(self: Box<Self>, hash_map: Arc<Mutex<BaseDeDatos>>) : ResultadoRedis;
}

class ComandoKeyHandler ##[bold] {}
class ComandoStringHandler ##[bold] {}
class ComandoListHandler ##[bold] {}
class ComandoSetHandler ##[bold] {}

ComandoHandler <<Abstract>>
ComandoHandler <|-- ComandoKeyHandler
ComandoHandler <|-- ComandoListHandler
ComandoHandler <|-- ComandoStringHandler
ComandoHandler <|-- ComandoSetHandler
@enduml
